/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app

import org.example.utilities.StringUtils

import org.apache.commons.text.WordUtils

//import org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication
// import org.springframework.stereotype.Controller
// import org.springframework.web.bind.annotation.GetMapping


@SpringBootApplication()
open class Application

fun main() {

    runApplication<Application>() // Start Spring Boot

    val tokens = StringUtils.split(MessageUtils.getMessage())
    val result = StringUtils.join(tokens)
    println(WordUtils.capitalize(result))
}

// @Controller
// class HomeController {
//     @GetMapping("/")
//     fun home(): String = "forward:/index.html"
// }