/*
 * This file was generated by the Gradle 'init' task.
 */

application {
    // Define the main class for the application.
    mainClass.set("org.example.app.AppKt")
}

plugins {
    kotlin("jvm")
    id("org.springframework.boot") version "3.2.2"
    id("io.spring.dependency-management") version "1.1.3"
    application
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.apache.commons:commons-text:1.10.0")
    implementation(project(":utilities"))
    implementation("org.springframework.boot:spring-boot-starter-web")
    //implementation("org.springframework.boot:spring-boot-starter-data-jpa")
    implementation("org.springframework.boot:spring-boot-starter-security")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    //runtimeOnly("org.postgresql:postgresql") // For PostgreSQL, change if using MySQL or H2
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.2")
    implementation("org.jetbrains.kotlin:kotlin-reflect")
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}